---
- name: garantindo os pacotes principais
  package:
   name: 
    - docker-ce
    - nginx
    - python-pip

- name: instalando o docker-py
  pip:
   name: docker-py

- name: garantindo inicializacao dos servicos nginx e docker rodando
  service:
   name: "{{item}}"
   state: started
  with_items:
   - nginx
   - docker

